app1/urls.py
from django.urls import path
from app1.views import *

app_name = 'app1_hai'

urlpatterns = [
    path('app1_hai/',app1_hai,name='app1_hai'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name = 'app2_hello'

urlpatterns = [
    path('app2_hello/',app2_hello,name='app2_hello'),
]

project99/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2
from app1.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('string_s/',string_s,name='string_s'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def app1_hai(request):
    return render(request,'app1_hai.html')


def string_s(request):
    return HttpResponse('this is geniric')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_hello(request):
    return render(request,'app2_hello.html')

templates/app1_hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is hai page</h1>
        <h2>navigation</h2>
        <a href="{% url 'app2_hello:app2_hello'%}">go to hello</a>
        <a href="{% url 'string_s'%}">go to hello</a>

    </center>
</body>
</html>

templates/app2_hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is hello page</h1>
        <h2>navigation</h2>
        <a href="{% url 'app1_hai:app1_hai'%}">go to hai</a>
        <a href="{% url 'string_s'%}">go to strike</strike></a>
    </center>
</body>
</html>